# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-simulator:
    build:
      target: development
    image: aphw-ddi-simulator-development
    container_name: aphw-ddi-simulator-development
    ports:
      - "8443:3000"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json