{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-simulator.container-secret") -}}
{{- define "aphw-ddi-simulator.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
  EMAIL: {{ .Values.container.email | quote }}
{{- end -}}
