# Required values to support CI pipeline
environment: production
environmentCode:
name: aphw-ddi-simulator
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-simulator

appInsights:
  connectionString:

labels:
  component: service

containerConfigMap:
  name: aphw-ddi-simulator-config-map

containerSecret:
  name: aphw-ddi-simulator-container-secret
  type: Opaque

deployment:
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 1250Mi

port: &port 3000

container:
  resourceTier: M
  port: *port
  simulatorUrl: dummy
  email: user@example.com
  redirectUrls: dummy
  postLogoutRedirectUrl: dummy

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 120

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 120

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

ingress:
  class: nginx
  endpoint: ffc-pay-request-editor
  server: example.com

service:
  port: 80
  type: ClusterIP

azureAppRegistration:
  enabled: true
  clientId:
  clientSecret:
  tenantId:
  redirectUrl: authenticate
