# Required values to support CI pipeline
environment: production
environmentCode:
name: aphw-ddi-simulator
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-simulator

appInsights:
  connectionString:

labels:
  component: service

containerConfigMap:
  name: aphw-ddi-simulator-config-map

containerSecret:
  name: aphw-ddi-simulator-container-secret
  type: Opaque

deployment:
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 2250Mi

container:
  resourceTier: M
  port: 3000
  simulatorUrl: dummy
  email: user@example.com
  redirectUrls: dummy
  postLogoutRedirectUrl: dummy

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: aphw-ddi-simulator
  server: example.com

workloadIdentity: true